### PR TITLE
[FLAGON-330] adds page load log containing page load time

### PR DESCRIPTION
**Pull request by UncleGedd**
## Adds page load stat: [JIRA ticket](https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=324&projectKey=FLAGON&view=detail&selectedIssue=FLAGON-330), [Github issue](https://github.com/apache/incubator-flagon-useralejs/issues/15)

- Adds a function inside of `setup()` that packages and sends a log containing a `pageLoadTime`. The log is sent when a page is loaded.
- Calculates page load time inside of `main.js`, calculation seems to be accurate in comparison to Chrome's dev tools.

I understand this PR is minimal. Let me know if there are anymore features I can add to better capture what users are asking for with respect to page load metrics.

### CODE REVIEW

**Comment by poorejc** [comment]
Cool! I'll check this PR out tomorrow and get it pushed. Great stuff! Thanks. I'm certain I can push out a few more tix if your interested. You can also feel free to hit me up on dev@flagon.apache.org (dev-subscribe@flagon.apache.org) and tell us what you're using Flagon for and what you'd like to see! We also have a user list (user-subscribe@flagon.apache.org) that will alert you to new releases at src and through npm (2.1.1 is in the final bout of our VOTE and will get pushed next week I think).

**Review by poorejc — COMMENTED** [review]
This is a really nice add, and big +1 for writing unit tests to go along with the add. Really great. However, I think in the interest of limiting redundant code, we should use our packageCustomLog funcion to push the page load log. PackageCustomLog (in scr/packageLog.js) lets you assign user defined key:value to canonical userale meta data. 

Here is an example:

`
document.addEventListener('change', function(e) {
    if (e.target.value === 'packageCustomLog') {
        window.userale.packageCustomLog({
            customLabel: 'packageCustomLog Example',
            customField1: 'foo',
            customField2: 'bar'},
            function(){return {'foo': 'bar', 'bar': 'foo'}},
            true
            );
    } else {
        return false
    }
});

`

We could save some SLOC doing it this way. I'm happy to do the refactor and service the pull request tomorrow. Thanks again @UncleGedd! Great work! Let me know if you want to get more involved with the project.

**Comment by UncleGedd** [comment]
Thanks for the feedback @poorejc! If you don't mind, I'll take care of the refactor sometime this weekend; it'll give me a chance to explore more of the code base.

**Comment by poorejc** [comment]
That's great @UncleGedd many thanks. Should be an easy one and I hope you understand the request. Your effort is much appreciated. If you want some pointers, just ask. Happy to put in work when other people are willing to. Thanks, again@

**Comment by poorejc** [comment]
THanks man! I'll take a look at the new commit tonight!

**Comment by poorejc** [comment]
Hi @UncleGedd thanks again for the work. I tested this tonight, and I'm afraid I found a bug in unit tests that traces back to your last PR. The error is in https://github.com/apache/incubator-flagon-useralejs/blob/395270fb683332f4ac75ade35d6ccb6e9beea78a/test/getInitialSettings_spec.js#L80

Looks like this: 

getInitialSettings
      ✓ fetches all settings from a script tag (164ms)
Error: Could not load script: "file://./build/userale-2.1.1.min.js"

The test output looks like this:
  1) getInitialSettings
       getInitialSettings
         grabs user id from params:
     TypeError: Cannot read property 'options' of undefined
      at _callee2$ (test/getInitialSettings_spec.js:82:47)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

I found this after dumping package-lock and regenerating through 'npm install' (not sure how I missed this in testing... apologies). Tests execute as written with the package-lock intact following your push. But, regenerating package-lock from our package.json breaks this one unit test. Could be you had additional npm modules loaded locally that were built into the package-lock.

I confirmed by regression testing against your PR commit:
git checkout 85b0219d1b4a01ea59e09ca757e27b84cce6b414

Looks like the url passed into this particular test doesn't pull the right resource (script). https://github.com/apache/incubator-flagon-useralejs/blob/395270fb683332f4ac75ade35d6ccb6e9beea78a/test/getInitialSettings_spec.js#L80

Previously we had configured this test to run against a URL with external assets (localhost:8080), not the (userale) script file path itself. https://github.com/apache/incubator-flagon-useralejs/blob/b6d62f8c7c817a065ba9577b9b0909efeb681b7f/test/testUtils.js#L47' Then again, it seems that some delta between your npm modules and the ones called through our package.json makes this run... 

I mucked about with the url configs to point at "file://../build/userale-2.1.1.min.js", and maybe find a workaroud, but test still fails. Giving up on it tonight as I'm struggling to find good examples of usage for this config in JSDOM literature.

If you have a moment and can look into it on your end see if it occurs to you if there is a package that you forgot to add to package.json... that would be much appreciated--then can commit back into this PR request and I'll test again tomorrow night. Thanks!

**Comment by UncleGedd** [comment]
Great points @poorejc. I also had trouble finding a good example in the JSDOM literature. Once we fix whatever is going awry with the NPM deps, I'd like to propose a refactor of our journey tests using something like `puppeteer` or `cypress`. 

I'll do some testing today and push up a fix soon to get that test passing

**Comment by poorejc** [comment]
Haven't forgotten about this, but need a night. Tomorrow, I'll push this PR to test and open up new branches to help resolve the unit test issue. Hopefully, that makes it a little easier to do some forensics on the node package tree. The A/B test strongly suggests that regardless of whether the unit test is written correctly, it's performing differently based on a difference in the package-lock.

**Comment by poorejc** [comment]
> Great points @poorejc. I also had trouble finding a good example in the JSDOM literature. Regarding pointing the test to `localhost:8080`, I'm getting a connection refused error whenever I use that syntax. Which makes sense because I'm not running anything on that port.
> 
> Once we fix whatever is going awry with the NPM deps, I'd like to propose a refactor of our journey tests using something like `puppeteer` or `cypress`.
> 
> I'll regen the `package-lock.json` file and push up a fix to get that test passing

I *just* had a user reach out about cypress. Might be able to get some examples, too to get us started. Would be very interested in that and any help you're interested in providing. Again, I'll take care of this PR very soon. Thanks for patience!

**Comment by UncleGedd** [comment]
Cool, I also sent you an email at dev@flagon.apache.org.

**Comment by poorejc** [comment]
> Cool, I also sent you an email at [dev@flagon.apache.org](mailto:dev@flagon.apache.org).

Sorry, I don't see your question on dev@ did you subscribe to the list? dev-subscribe@flagon.apache.org. Then email dev@flagon.apache.org.

**Comment by poorejc** [comment]
Thanks @UncleGedd your PR fixed unit tests too. Dir Name ... who'd have thunk!? :) Thanks again!

**Pull request merged**
